# Generated by Django 3.2.6 on 2021-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.PositiveIntegerField(verbose_name='Cantidad de productos vendidos')),
                ('Fecha', models.CharField(max_length=100, verbose_name='Fecha de la venta')),
                ('PrecioFinal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio final de la venta')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
    ]
