# Generated by Django 3.2.6 on 2021-09-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgProducto', models.ImageField(blank=True, null=True, upload_to='')),
                ('DescripcionProducto', models.CharField(max_length=100, verbose_name='Descripción del producto')),
                ('PrecioCompra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra del producto')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta del producto')),
                ('FechaUIngreso', models.CharField(max_length=100, verbose_name='Fecha de ingreso del producto')),
                ('Talla', models.CharField(max_length=100, verbose_name='Talla del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
