# Generated by Django 3.2.6 on 2021-09-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionCategoria', models.CharField(max_length=100, verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('ApellidoCliente', models.CharField(max_length=100, verbose_name='Apellido del cliente')),
                ('DireccionCliente', models.CharField(max_length=100, verbose_name='Dirección del cliente')),
                ('TelefonoCliente', models.CharField(max_length=100, verbose_name='Teléfono del cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionEstado', models.CharField(max_length=100, verbose_name='Descripción del estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionMarca', models.CharField(max_length=100, verbose_name='Descripción de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionMateriales', models.CharField(max_length=100, verbose_name='Descripción del material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaisOrigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionPais', models.CharField(max_length=100, verbose_name='Descripción del país')),
            ],
            options={
                'verbose_name': 'PaísOrigen',
                'verbose_name_plural': 'PaísesOrigen',
                'db_table': 'paises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProveedor', models.CharField(max_length=100, verbose_name='Nombre del proveedor')),
                ('DireccionProveedor', models.CharField(max_length=100, verbose_name='Dirección del proveedor')),
                ('TelefonoProveedor', models.CharField(max_length=100, verbose_name='Teléfono del proveedor')),
                ('EmailProveedor', models.CharField(max_length=100, verbose_name='Email del proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionRol', models.CharField(max_length=100, verbose_name='Descripción del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionTipoDoc', models.CharField(max_length=100, verbose_name='Descripción del tipo de documento')),
            ],
            options={
                'verbose_name': 'TipoDocumento',
                'verbose_name_plural': 'TiposDocumento',
                'db_table': 'tipodoc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgUsuario', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imágen del usuario')),
                ('NombreUsuario', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('ApellidoUsuario', models.CharField(max_length=100, verbose_name='Apellido del usuario')),
                ('TelefonoUsuario', models.CharField(max_length=100, verbose_name='Teléfono del usuario')),
                ('EmailUsuario', models.CharField(max_length=100, verbose_name='Email del usuario')),
                ('NumeroDocumento', models.CharField(max_length=100, verbose_name='Número de documento del usuario')),
                ('Usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('Contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='productos',
            name='ImgProducto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imágen del producto'),
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
    ]
