# Generated by Django 3.2.6 on 2021-09-12 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20210911_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.estado'),
        ),
    ]
