# Generated by Django 3.2.6 on 2021-09-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_rename_estado_productos_estados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='estados',
            new_name='Estado',
        ),
    ]
