# Generated by Django 3.2.6 on 2021-09-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_rename_estados_productos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Productos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.productos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Categorias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.categorias'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Marcas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.marcas'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Materiales',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.materiales'),
        ),
        migrations.AddField(
            model_name='productos',
            name='PaisOrigen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.paisorigen'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Proveedores',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.proveedores'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='Estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.estado'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.estado'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Roles',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.roles'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='TipoDocumento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.tipodocumento'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='Clientes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.clientes'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='Productos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.productos'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='Usuarios',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.usuarios'),
        ),
    ]
