# Generated by Django 4.0.3 on 2022-03-28 00:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionCategoria', models.CharField(max_length=100, verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('ApellidoCliente', models.CharField(max_length=100, verbose_name='Apellido del cliente')),
                ('BarrioCliente', models.CharField(max_length=100, verbose_name='Barrio del cliente')),
                ('DireccionCliente', models.CharField(max_length=100, verbose_name='Dirección del cliente')),
                ('TelefonoCliente', models.CharField(max_length=100, verbose_name='Teléfono del cliente')),
                ('ProductosFrecuentes', models.CharField(max_length=100, verbose_name='Productos que frecuenta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionEstado', models.CharField(max_length=100, verbose_name='Descripción del estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionMarca', models.CharField(max_length=100, verbose_name='Descripción de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionMateriales', models.CharField(max_length=100, verbose_name='Descripción del material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaisOrigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionPais', models.CharField(max_length=100, verbose_name='Descripción del país')),
            ],
            options={
                'verbose_name': 'País de Origen',
                'verbose_name_plural': 'Países de Origen',
                'db_table': 'paises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionRol', models.CharField(max_length=100, verbose_name='Descripción del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionTipoDoc', models.CharField(max_length=100, verbose_name='Descripción del tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipodoc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionMovimiento', models.CharField(max_length=100, verbose_name='Descripción del movimiento')),
            ],
            options={
                'verbose_name': 'TMovimiento',
                'verbose_name_plural': 'TMovimientos',
                'db_table': 'tipomovimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('TelefonoUsuario', models.CharField(max_length=100, verbose_name='Teléfono del usuario')),
                ('NumeroDocumento', models.CharField(max_length=100, verbose_name='Número de documento del usuario')),
                ('Estado', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.estado')),
                ('Roles', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.roles')),
                ('TipoDocumento', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tipodocumento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'myuser',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('ApellidoUsuario', models.CharField(max_length=100, verbose_name='Apellido del usuario')),
                ('TelefonoUsuario', models.CharField(max_length=100, verbose_name='Teléfono del usuario')),
                ('EmailUsuario', models.EmailField(max_length=100, verbose_name='Email del usuario')),
                ('NumeroDocumento', models.CharField(max_length=100, verbose_name='Número de documento del usuario')),
                ('Usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('Contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('Estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.estado')),
                ('Roles', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.roles')),
                ('TipoDocumento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.tipodocumento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProveedor', models.CharField(max_length=100, verbose_name='Nombre del proveedor')),
                ('DireccionProveedor', models.CharField(max_length=100, verbose_name='Dirección del proveedor')),
                ('TelefonoProveedor', models.CharField(max_length=100, verbose_name='Teléfono del proveedor')),
                ('EmailProveedor', models.EmailField(max_length=100, verbose_name='Email del proveedor')),
                ('Estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.estado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('DescripcionProducto', models.CharField(max_length=100, verbose_name='Descripción del producto')),
                ('PrecioCompra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra del producto')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta del producto')),
                ('FechaIngreso', models.CharField(max_length=100, verbose_name='Fecha de ingreso del producto')),
                ('Talla', models.CharField(max_length=100, verbose_name='Talla del producto')),
                ('Categorias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.categorias')),
                ('Estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.estado')),
                ('Marcas', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.marcas')),
                ('Materiales', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.materiales')),
                ('PaisOrigen', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.paisorigen')),
                ('Proveedores', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.proveedores')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaMovimiento', models.CharField(default='', max_length=100, verbose_name='Fecha del movimiento')),
                ('CantidadProductos', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('Clientes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.clientes')),
                ('Productos', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.productos')),
                ('Proveedores', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.proveedores')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalInventario', models.CharField(default='', max_length=100, verbose_name='Cantidad de productos en inventario')),
                ('Productos', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.productos')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
    ]
