# Generated by Django 3.2.9 on 2021-12-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionCategoria', models.CharField(max_length=100, verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('ApellidoCliente', models.CharField(max_length=100, verbose_name='Apellido del cliente')),
                ('BarrioCliente', models.CharField(max_length=100, verbose_name='Barrio del cliente')),
                ('DireccionCliente', models.CharField(max_length=100, verbose_name='Dirección del cliente')),
                ('TelefonoCliente', models.CharField(max_length=100, verbose_name='Teléfono del cliente')),
                ('ProductosFrecuentes', models.CharField(max_length=100, verbose_name='Productos que frecuenta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionEstado', models.CharField(max_length=100, verbose_name='Descripción del estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionMarca', models.CharField(max_length=100, verbose_name='Descripción de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionMateriales', models.CharField(max_length=100, verbose_name='Descripción del material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaisOrigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionPais', models.CharField(max_length=100, verbose_name='Descripción del país')),
            ],
            options={
                'verbose_name': 'País de Origen',
                'verbose_name_plural': 'Países de Origen',
                'db_table': 'paises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('DescripcionProducto', models.CharField(max_length=100, verbose_name='Descripción del producto')),
                ('PrecioCompra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra del producto')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta del producto')),
                ('CantidadProductos', models.PositiveIntegerField(null=True, verbose_name='Cantidad de productos comprados')),
                ('FechaIngreso', models.CharField(max_length=100, verbose_name='Fecha de ingreso del producto')),
                ('Talla', models.CharField(max_length=100, verbose_name='Talla del producto')),
                ('Categorias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.categorias')),
                ('Estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.estado')),
                ('Marcas', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.marcas')),
                ('Materiales', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.materiales')),
                ('PaisOrigen', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.paisorigen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionRol', models.CharField(max_length=100, verbose_name='Descripción del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionTipoDoc', models.CharField(max_length=100, verbose_name='Descripción del tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipodoc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=100, verbose_name='Fecha de la venta')),
                ('DescripcionVenta', models.CharField(max_length=100, verbose_name='Descripción de la venta')),
                ('Cantidad', models.PositiveIntegerField(verbose_name='Cantidad de productos vendidos')),
                ('PrecioFinal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio final de la venta')),
                ('Clientes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.clientes')),
                ('Productos', models.ManyToManyField(blank=True, default='', to='InventoryApp.Productos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('ApellidoUsuario', models.CharField(max_length=100, verbose_name='Apellido del usuario')),
                ('TelefonoUsuario', models.CharField(max_length=100, verbose_name='Teléfono del usuario')),
                ('EmailUsuario', models.EmailField(max_length=100, verbose_name='Email del usuario')),
                ('NumeroDocumento', models.CharField(max_length=100, verbose_name='Número de documento del usuario')),
                ('Usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('Contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('Estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.estado')),
                ('Roles', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.roles')),
                ('TipoDocumento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.tipodocumento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProveedor', models.CharField(max_length=100, verbose_name='Nombre del proveedor')),
                ('DireccionProveedor', models.CharField(max_length=100, verbose_name='Dirección del proveedor')),
                ('TelefonoProveedor', models.CharField(max_length=100, verbose_name='Teléfono del proveedor')),
                ('EmailProveedor', models.EmailField(max_length=100, verbose_name='Email del proveedor')),
                ('Estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.estado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='Proveedores',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.proveedores'),
        ),
    ]
