# Generated by Django 3.2.9 on 2021-12-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('InventoryApp', '0003_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customUser',
            new_name='customu',
        ),
    ]
