# Generated by Django 3.2.9 on 2021-12-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_rename_customuser_customu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customu',
        ),
    ]
