# Generated by Django 3.2.9 on 2021-12-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0006_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
