# Generated by Django 3.2.6 on 2021-09-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('Description', models.CharField(max_length=100, verbose_name='Descripción de la Categoría')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('Stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('Description', models.CharField(max_length=100, verbose_name='Descripción del Producto')),
                ('State', models.CharField(max_length=20, verbose_name='Estado del Producto')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catandprod.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
    ]
