# Generated by Django 3.2.6 on 2021-09-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catandprod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
